### ISSUE TITLE
Update API resources and tests to reflect data layer changes

### ISSUE THREAD

**Issue by siggirh** [rudatalab/python-objectcube#47]
## Description

After the data layer API changes that were made recently, we need to confirm the API resources are correctly reflecting the modified data layer API.
We also need to add more tests to the API to make the coverage more thorough, even though it's 100%.
## Tasks

The following tasks need to be done (and possibly more added later). Each can be ticked when that has been resolved.
### Concept Resource
- [x] Verify the resource is working correctly. (#46)
- [x] Update tests to be more thorough. (#46)
### Tag Resource
- [ ] Verify the resource is working correctly.
- [ ] Update tests to be more thorough.
### Object Resource
- [ ] Verify the resource is working correctly.
- [ ] Update tests to be more thorough.
